#!/usr/bin/env bash

set -euo pipefail

REQUIRED_GO_VERSION="${REQUIRED_GO_VERSION:-1.26.3}"
REQUIRED_GORELEASER_VERSION="${REQUIRED_GORELEASER_VERSION:-v2.16.0}"
REQUIRED_ACTIONLINT_VERSION="${REQUIRED_ACTIONLINT_VERSION:-v1.7.12}"
REQUIRED_GOVULNCHECK_VERSION="${REQUIRED_GOVULNCHECK_VERSION:-v1.1.4}"
MANUAL_STEPS_FILE="${MANUAL_STEPS_FILE:-.codex/state/manual-admin-steps.sh}"

failures=0

log() {
  echo "[dev-env] $*"
}

record_manual_step() {
  local message=$1
  mkdir -p "$(dirname "$MANUAL_STEPS_FILE")"
  if [[ ! -f "$MANUAL_STEPS_FILE" ]]; then
    cat >"$MANUAL_STEPS_FILE" <<'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/dev-env-check.sh.
# Review each command before running it.

SCRIPT
    chmod +x "$MANUAL_STEPS_FILE"
  fi
  printf '\n# %s\n' "$message" >>"$MANUAL_STEPS_FILE"
}

require_command() {
  local name=$1
  if ! command -v "$name" >/dev/null 2>&1; then
    log "missing command: $name"
    failures=$((failures + 1))
    return 1
  fi
  log "$name: $(command -v "$name")"
}

check_go() {
  require_command go || return
  local version
  version="$(go version | awk '{print $3}' | sed 's/^go//')"
  log "go version: $version"
  if [[ "$version" != "$REQUIRED_GO_VERSION" ]]; then
    log "expected Go $REQUIRED_GO_VERSION"
    failures=$((failures + 1))
  fi
}

check_gh() {
  require_command gh || return
  if ! gh auth status >/dev/null 2>&1; then
    log "GitHub authentication is missing or invalid."
    record_manual_step "Authenticate GitHub CLI for this repository user."
    printf '%s\n' 'gh auth login' >>"$MANUAL_STEPS_FILE"
    failures=$((failures + 1))
  else
    log "GitHub authentication: ok"
  fi
}

check_goreleaser() {
  require_command goreleaser || return
  if ! goreleaser --version | grep -q "GitVersion:    ${REQUIRED_GORELEASER_VERSION}"; then
    log "expected GoReleaser $REQUIRED_GORELEASER_VERSION"
    failures=$((failures + 1))
  fi
}

check_actionlint() {
  require_command actionlint || return
  local version
  version="$(actionlint -version | head -n1)"
  if [[ "$version" != "$REQUIRED_ACTIONLINT_VERSION" ]]; then
    log "expected actionlint $REQUIRED_ACTIONLINT_VERSION, got $version"
    failures=$((failures + 1))
  fi
}

check_govulncheck() {
  require_command govulncheck || return
  if ! govulncheck -version | grep -q "Scanner: govulncheck@${REQUIRED_GOVULNCHECK_VERSION}"; then
    log "expected govulncheck $REQUIRED_GOVULNCHECK_VERSION"
    failures=$((failures + 1))
  fi
}

check_gitleaks() {
  require_command gitleaks || return
  log "gitleaks installed; source builds may not embed the version string."
}

main() {
  check_go
  check_gh
  check_goreleaser
  check_gitleaks
  check_actionlint
  check_govulncheck

  if [[ "$failures" -ne 0 ]]; then
    log "$failures environment check(s) failed."
    if [[ -f "$MANUAL_STEPS_FILE" ]]; then
      log "manual steps written to $MANUAL_STEPS_FILE"
    fi
    exit 1
  fi

  log "development environment is ready."
}

main "$@"
